### ISSUE TITLE
Error on startup `this[#remain].subarray is not a function`

### ISSUE THREAD

**Issue by ray-x** [Shougo/ddc.vim#41]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
Error message:
[denops] Unexpected error occured in session: TypeError: this[#remain].subarray is not a function                                                                 

It is may related to deno version. I have deno 1.13.1 installed

## Expected
No error

## Environment Information

 * ddc version (SHA1): 
latest
 * OS: Mac

 * neovim/Vim `:version` output:
NVIM v0.6.0-dev+205-g9695691ee-dirty                                                                                                                              
Build type: Release                                                                                                                                               
LuaJIT 2.1.0-beta3         
 * `:checkhealth` or `:CheckHealth` result(neovim only):
health#denops#check
========================================================================
  - INFO: Supported Deno version: `1.11.0`
  - INFO: Detected Deno version: `1.8.2`
  - ERROR: Unsupported Deno version is detected. You need to upgrade it to `1.11.0` or later.
  - INFO: Supported Neovim version: `0.4.4`
  - INFO: Detected Neovim version: `0.6.0`
  - OK: Neovim version check: passed
  - INFO: Denops status: `running`
  - OK: Denops status check: passed

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set termguicolors

call plug#begin('~/.vim/plugged')
Plug 'ray-x/guihua.lua'
Plug 'ray-x/navigator.lua'
Plug 'ray-x/aurora'
Plug 'Shougo/ddc.vim'
Plug 'vim-denops/denops.vim'
Plug 'Shougo/ddc-around'
Plug 'Shougo/ddc-matcher_head'
Plug 'Shougo/ddc-sorter_rank'
Plug 'Shougo/deoppet.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'Shougo/neco-vim'
Plug 'Shougo/ddc-nvim-lsp'
Plug 'Shougo/ddc-nextword'
Plug 'matsui54/ddc-buffer'
Plug 'matsui54/ddc-nvim-lsp-doc'
Plug 'matsui54/ddc-dictionary'
call plug#end()

call ddc#custom#patch_global('sources', ['around'])
call ddc#custom#patch_global('sources', ['nvimlsp'])
  call ddc#custom#patch_global('sourceOptions', {
  \ '_': { 'matchers': ['matcher_head'] },
  \ 'nvimlsp': { 'mark': 'lsp', 'forceCompletionPattern': '\.|:|->' },
  \ })

call ddc#custom#patch_global('sourceParams', {
  \ 'nvimlsp': { 'kindLabels': { 'Class': 'c' } },
  \ })
inoremap <silent><expr> <TAB>
  \ pumvisible() ? '<C-n>' :
  \ (col('.') <= 1 <Bar><Bar> getline('.')[col('.') - 2] =~# '\s') ?
  \ '<TAB>' : ddc#manual_complete()
  
inoremap <expr><S-TAB>  pumvisible() ? '<C-p>' : '<C-h>'
call ddc#enable()
```

**Comment by Shougo** [comment]
> It is may related to deno version. I have deno 1.13.1 installed

I use deno `1.13.2` and it works.

**Comment by Shougo** [comment]
> INFO: Detected Deno version: 1.8.2
> ERROR: Unsupported Deno version is detected. You need to upgrade it to 1.11.0 or later.

Please use the latest Deno version.  It is not supported version.

> It is may related to deno version. I have deno 1.13.1 installed

Why you use `1.8.2` version instead?  Please explain it.

**Comment by Shougo** [comment]
```
health#denops#check
========================================================================
  - INFO: Supported Deno version: `1.11.0`
  - INFO: Detected Deno version: `1.13.2`
  - OK: Deno version check: passed
  - INFO: Supported Neovim version: `0.4.4`
  - INFO: Detected Neovim version: `0.6.0`
  - OK: Neovim version check: passed
  - INFO: Denops status: `running`
  - OK: Denops status check: passed

```

It is my output.

**Comment by ray-x** [comment]
Ok, seem I do have multiple version of deno installed and I removed the older version.
But still have same issue:
```
deno --version
deno 1.13.2 (release, x86_64-apple-darwin)
v8 9.3.345.11
typescript 4.3.5
```

```
health#denops#check
========================================================================
  - INFO: Supported Deno version: `1.11.0`
  - INFO: Detected Deno version: `1.13.2`
  - OK: Deno version check: passed
  - INFO: Supported Neovim version: `0.4.4`
  - INFO: Detected Neovim version: `0.6.0`
  - OK: Neovim version check: passed
  - INFO: Denops status: `running`
  - OK: Denops status check: passed

health#denops#check
========================================================================
  - INFO: Supported Deno version: `1.11.0`
  - INFO: Detected Deno version: `1.13.2`
  - OK: Deno version check: passed
  - INFO: Supported Neovim version: `0.4.4`
  - INFO: Detected Neovim version: `0.6.0`
  - OK: Neovim version check: passed
  - INFO: Denops status: `running`
  - OK: Denops status check: passed

health#nvim#check
========================================================================
## Configuration
  - WARNING: Missing user config file: /Users/ray/.config/nvim/init.vim
    - ADVICE:
      - :help |init.vim|

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

```


The error messages:

```
[denops] error: Uncaught (in worker "ddc") (in promise) NotFound: No such file or directory (os error 2)                                                                                                                                                                                    
[denops]     this._proc = Deno.run({                                                                                                                                                                                                                                                        
[denops]                       ^                                                                                                                                                                                                                                                            
[denops]     at deno:core/01_core.js:106:46                                                                                                                                                                                                                                                 
[denops]     at unwrapOpResult (deno:core/01_core.js:126:13)                                                                                                                                                                                                                                
[denops]     at Object.opSync (deno:core/01_core.js:140:12)                                                                                                                                                                                                                                 
[denops]     at opRun (deno:runtime/js/40_process.js:27:17)                                                                                                                                                                                                                                 
[denops]     at Object.run (deno:runtime/js/40_process.js:112:17)                                                                                                                                                                                                                           
[denops]     at new Source (file:///Users/ray/.vim/plugged/ddc-nextword/denops/ddc-sources/nextword.ts:16:23)                                                                                                                                                                            
[denops]     at Ddc.registerSource (file:///Users/ray.xu/.vim/plugged/ddc.vim/denops/ddc/ddc.ts:147:20)                                                                                                                                                                                     
[denops] error: Uncaught (in promise) Error: Unhandled error event reached main worker.                                                                                                                                                                                                     
[denops]     at Worker.#pollControl (deno:runtime/js/11_workers.js:261:23)                                                                                                                                                                                                                  
[denops] server terminated unexpectedly: 1                                                                                                                                                                                                                                                  
Error detected while processing function denops#notify[1]..denops#server#notify:                                                                                                                                                                                                            
line    2:                                                                                                                                                                                                                                                                                  
E605: Exception not caught: The server is not ready yet                                                                                                                                                                                                                                     
Error detected while processing function denops#notify[1]..denops#server#notify:                                                                                                                                                                                                            
line    2:                                                                                                                                                                                                                                                                                  
E605: Exception not caught: The server is not ready yet             
```

**Comment by ray-x** [comment]
FYI
It seems `nextword` source is not behaving correctly. After I remove that it is fine now.

**Comment by Shougo** [comment]
Please read ddc-nextword documentation.
https://github.com/Shougo/ddc-nextword

`nextword` binary is required.  No magic.

**Comment by ray-x** [comment]
In fact even with nextword install but with no NEXTWORD_DATA_PATH setup. I still got errors.

So from my point of view, there are two issues:
1)  I did not enable nextword as a source. But nextword crash the ddc.vim
2) Would be better that the plugin does not crash even if some sources failed. Instead, showing warning messages would be helpful.

**Comment by Shougo** [comment]
I have fixed both problems.  Closing.
